"""Actant - 基于 Actor 模型的跨平台通用分布式任务编排引擎。

采用 Effect-Resource-Handler 统一扩展架构：所有扩展点（Routing、Scheduling、
Transport、Store、Actor、Lifecycle）统一为 `Capability`（能力声明）+ `Handler`
（能力实现）+ `Layer`（handler 组合）+ `Effect`（请求能力）。

典型用法::

    import actant

    rt = actant.Runtime()
    rt.layer("Routing").chain(my_router)
    rt.layer("TaskLifecycle").chain(lambda e: print(f"task {e.kind}: {e.task_id}"))
    rt.start()

    # 在 handler 中请求 capability：
    target = actant.ask("Routing", ctx)
    actant.emit("TaskLifecycle", task_event)

"""

from __future__ import annotations

from actant._effects import (
    ask,
    ask_async,
    effect,
    emit,
    impossible,
    perform,
    perform_async,
    perform_batch_async,
)
from actant._runtime import Layer, Runtime, get_current_runtime, require_runtime, use_runtime
from actant.actant import get_version
from actant.actant import prometheus_text as metrics_text
from actant.capabilities import (
    ACTOR_LIFECYCLE,
    ACTOR_MESSAGING,
    ACTOR_SUPERVISION,
    BUILTIN_CAPABILITIES,
    EXECUTE,
    NODE_LIFECYCLE,
    PYTHON_ONLY_CAPABILITIES,
    RETRY_POLICY,
    ROUTING,
    RUST_BACKED_CAPABILITIES,
    SCHEDULING,
    SERIALIZATION,
    STORE,
    TASK_LIFECYCLE,
    TRANSPORT,
    WORKFLOW_LIFECYCLE,
    ActorEvent,
    ActorFailureCtx,
    ActorLifecycleHandler,
    ActorMessageReq,
    ActorMessagingHandler,
    ActorSupervisionHandler,
    CapabilityMeta,
    EffectKind,
    ExecuteCtx,
    ExecuteHandler,
    ExecuteOutcome,
    NodeEvent,
    NodeLifecycleHandler,
    RetryCtx,
    RetryPolicyHandler,
    RouteCtx,
    RoutingHandler,
    ScheduleCtx,
    SchedulingHandler,
    SerializationHandler,
    SerializationReq,
    StoreHandler,
    StoreReq,
    TaskEvent,
    TaskLifecycleHandler,
    TransportHandler,
    TransportReq,
    WorkflowEvent,
    WorkflowLifecycleHandler,
    get_builtin_capability_meta,
)
from actant.exceptions import (
    ActantError,
    ActantTimeoutError,
    ActorError,
    AlreadyExistsError,
    ConfigError,
    InternalError,
    InvalidStateError,
    MetricsError,
    NetworkError,
    NotFoundError,
    PayloadTooLargeError,
    SerializationError,
    StorageError,
    TaskCancelledError,
    TaskError,
    WorkerError,
    WorkflowCancelledError,
    WorkflowError,
    WorkflowFailedError,
)
from actant.flow import current_workflow_id, flow
from actant.task import (
    AsyncResult,
    Task,
    TaskContext,
    TaskState,
    gather,
    gather_async,
    get_task_context,
    task,
)

__version__ = get_version()

__all__ = [
    "ACTOR_LIFECYCLE",
    "ACTOR_MESSAGING",
    "ACTOR_SUPERVISION",
    "BUILTIN_CAPABILITIES",
    "EXECUTE",
    "NODE_LIFECYCLE",
    "PYTHON_ONLY_CAPABILITIES",
    "RETRY_POLICY",
    "ROUTING",
    "RUST_BACKED_CAPABILITIES",
    "SCHEDULING",
    "SERIALIZATION",
    "STORE",
    "TASK_LIFECYCLE",
    "TRANSPORT",
    "WORKFLOW_LIFECYCLE",
    "ActantError",
    "ActantTimeoutError",
    "ActorError",
    "ActorEvent",
    "ActorFailureCtx",
    "ActorLifecycleHandler",
    "ActorMessageReq",
    "ActorMessagingHandler",
    "ActorSupervisionHandler",
    "AlreadyExistsError",
    "AsyncResult",
    "CapabilityMeta",
    "ConfigError",
    "EffectKind",
    "ExecuteCtx",
    "ExecuteHandler",
    "ExecuteOutcome",
    "InternalError",
    "InvalidStateError",
    "Layer",
    "MetricsError",
    "NetworkError",
    "NodeEvent",
    "NodeLifecycleHandler",
    "NotFoundError",
    "PayloadTooLargeError",
    "RetryCtx",
    "RetryPolicyHandler",
    "RouteCtx",
    "RoutingHandler",
    "Runtime",
    "ScheduleCtx",
    "SchedulingHandler",
    "SerializationError",
    "SerializationHandler",
    "SerializationReq",
    "StorageError",
    "StoreHandler",
    "StoreReq",
    "Task",
    "TaskCancelledError",
    "TaskContext",
    "TaskError",
    "TaskEvent",
    "TaskLifecycleHandler",
    "TaskState",
    "TransportHandler",
    "TransportReq",
    "WorkerError",
    "WorkflowCancelledError",
    "WorkflowError",
    "WorkflowEvent",
    "WorkflowFailedError",
    "WorkflowLifecycleHandler",
    "__version__",
    "ask",
    "ask_async",
    "current_workflow_id",
    "effect",
    "emit",
    "flow",
    "gather",
    "gather_async",
    "get_builtin_capability_meta",
    "get_current_runtime",
    "get_task_context",
    "impossible",
    "metrics_text",
    "perform",
    "perform_async",
    "perform_batch_async",
    "require_runtime",
    "task",
    "use_runtime",
]
